### ISSUE TITLE
大佬6666

### ISSUE THREAD

**Issue by sidian123** [shiniaxiaomi/AutoCommitToGithub#1]
双击666
![img](https://ss0.bdstatic.com/94oJfD_bAAcT8t7mm9GUKT-xh_/timg?image&quality=100&size=b4000_4000&sec=1566874305&di=9c4e691988c9b5da97486b5233585490&src=http://tva2.sinaimg.cn/crop.0.0.711.400/90eb2137ly1fm7ety8ue6j20jr0b4ac8.jpg)

**Comment by shiniaxiaomi** [comment]
单机777

**Comment by sidian123** [comment]
哟呵
![啊啊](https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1566884575276&di=1f70df8ba2c2d3a36da79db11ef754ef&imgtype=0&src=http%3A%2F%2Fb-ssl.duitang.com%2Fuploads%2Fitem%2F201611%2F26%2F20161126142316_3vjxH.thumb.700_0.jpeg)
